version: '3.3'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://mongodb:27017/ecommerce
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  backend-test:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: ["pytest", "--maxfail=1", "--disable-warnings", "--tb=short", "--capture=tee-sys", "--junitxml=/usr/src/app/logs/pytest-report.xml"]
    volumes:
      - ./backend:/usr/src/app
      - ./backend/logs:/usr/src/app/logs
    environment:
      - API_BASE=http://backend:10000
      - NODE_ENV=test
      - MONGO_URI=mongodb://mongodb:27017/ecommerce
    depends_on:
      - backend
      - mongodb

  frontend-test:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    command: ["npm", "run", "test:coverage"]
    volumes:
      - ./frontend:/app
      - ./frontend/html-report:/app/html-report
      - ./frontend/jest-stare:/app/jest-stare
    environment:
      - CI=true
    depends_on:
      - frontend

volumes:
  mongodb_data:
